// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Publisher is an autogenerated mock type for the Publisher type
type Publisher struct {
	mock.Mock
}

// UserUpvoted provides a mock function with given fields: cat, itemID, votes
func (_m *Publisher) UserUpvoted(cat string, itemID string, votes int64) error {
	ret := _m.Called(cat, itemID, votes)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int64) error); ok {
		r0 = rf(cat, itemID, votes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
